### ISSUE TITLE
[NUXT] document is not defined

### ISSUE THREAD

**Issue by pouyamiralayi** [talkhabi/vue-persian-datetime-picker#78]
Hi there! i am in a Nuxt.js environment and i have already wrapped my ``<date-picker v-model="dateFrom"></date-picker>``
inside ``<client-only>`` tags but vue still bothers me with: ``document is not defined``.
full log below:
```
 WARN  [vue-router] Failed to resolve async component default: ReferenceError: document is not defined        16:18:20


 WARN  [vue-router] uncaught error during route navigation:                                                   16:18:20


 ERROR  document is not defined                                                                               16:18:20

  at o (node_modules\vue-persian-datetime-picker\dist\vue-persian-datetime-picker.js:1:33308)
  at n (node_modules\vue-persian-datetime-picker\dist\vue-persian-datetime-picker.js:1:33139)
  at t.exports (node_modules\vue-persian-datetime-picker\dist\vue-persian-datetime-picker.js:1:34820)
  at Object.<anonymous> (node_modules\vue-persian-datetime-picker\dist\vue-persian-datetime-picker.js:1:20799)
  at e (node_modules\vue-persian-datetime-picker\dist\vue-persian-datetime-picker.js:1:530)
  at Object.<anonymous> (node_modules\vue-persian-datetime-picker\dist\vue-persian-datetime-picker.js:1:1841)
  at e (node_modules\vue-persian-datetime-picker\dist\vue-persian-datetime-picker.js:1:530)
  at Object.<anonymous> (node_modules\vue-persian-datetime-picker\dist\vue-persian-datetime-picker.js:1:20627)
  at e (node_modules\vue-persian-datetime-picker\dist\vue-persian-datetime-picker.js:1:530)
  at node_modules\vue-persian-datetime-picker\dist\vue-persian-datetime-picker.js:1:893
  at node_modules\vue-persian-datetime-picker\dist\vue-persian-datetime-picker.js:1:902
  at node_modules\vue-persian-datetime-picker\dist\vue-persian-datetime-picker.js:1:143
  at Object.<anonymous> (node_modules\vue-persian-datetime-picker\dist\vue-persian-datetime-picker.js:1:376)
  at Module._compile (internal/modules/cjs/loader.js:945:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
  at Module.load (internal/modules/cjs/loader.js:798:32)
```
BTW i have initialized datetime-picker by leveraging from Nuxt.js plugins. i have also configured webpack to not include moment locale the way specified in your docs.
thanks!

**Comment by pouyamiralayi** [comment]
for those who experience the same issue, this is how i solved it:
```
components: {
        datePicker: () => import('vue-persian-datetime-picker'),
}
```
cheers!
